name: dictionary
version: 1.0.0
description: Dictionary Plugin for PolymorphicBot
dependencies:
  http: '>=0.11.1+1 <0.12.0'
  polymorphic_bot:
    git: git://github.com/PolymorphicBot/PolymorphicBot.git
